# Generated by Django 6.0.3 on 2026-04-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo_url',
            field=models.URLField(blank=True, help_text="Paste a direct image URL here (e.g. from Imgur or Google Drive) — use this instead of uploading if images aren't working", null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_url',
            field=models.URLField(blank=True, help_text='Paste a direct link to your resume PDF (e.g. Google Drive share link)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, help_text='Paste a direct image URL instead of uploading', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Motivated BCA student with strong technical and problem-solving skills.'),
        ),
    ]
